version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/poetry"
    schedule:
      interval: "daily"
    versioning-strategy: lockfile-only
