# Generated by Django 4.2.10 on 2024-03-01 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Productivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=200)),
                (
                    "frequency",
                    models.IntegerField(
                        choices=[
                            (0, "Key"),
                            (1, "Loop"),
                            (2, "Day"),
                            (3, "Week"),
                            (4, "Month"),
                        ]
                    ),
                ),
                ("group", models.CharField(max_length=200)),
                ("last_check", models.DateTimeField(auto_now=True)),
                (
                    "last_check_undo",
                    models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
                ),
            ],
        ),
    ]
